version: "3"
 
services:
  db:
    image: postgres:11.5-alpine
    container_name: postgres-db 
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres1234
      - PGPASSWORD=postgres1234
      - POSTGRES_DB=testdb
      - DATABASE_HOST=localhost
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d